name: Submit website PR
on: [push, pull_request]
jobs:
  build:
    if: github.repository == 'nikhilwoodruff/analysis-template'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: reponame
          environment-file: environment.yml
          python-version: 3.9
          auto-activate-base: false

      - name: Build
        run: |
          git config --global user.name "ubicenter[bot]"
          cd ..
          git clone https://github.com/nikhilwoodruff/ubicenter.org
          cd ubicenter.org
          git remote add origin https://ubicenter-post-bot:$GITHUB_TOKEN@github.com/ubicenter-post-bot/ubicenter.org
          git remote add upstream https://ubicenter-post-bot:$GITHUB_TOKEN@github.com/ubicenter/ubicenter.org
          cd ..
          python ./ubicenter.org/post_from_notebook.py analysis-template/website/post.ipynb analysis-template/website/metadata.yml --output-md ubicenter.org/_posts/$OUTPUT_MD --output-folder ubicenter.org/assets/markdown_assets/$OUTPUT_FOLDER/
          cd ubicenter.org
          git add .
          git commit -m "Add new post"
          git push origin main
          gh pr create --title "Auto-filed PR" --body "Filed automatically, to be removed if successful."
        env:
          GITHUB_TOKEN: ${{secrets.POST_BOT_GH_TOKEN}}
          OUTPUT_MD: 2021-07-07-test-post.md
          OUTPUT_FOLDER: test-post
