name: Submit website PR
on: [push, pull_request]
jobs:
  build:
    if: github.repository == 'nikhilwoodruff/analysis-template'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: reponame
          environment-file: environment.yml
          python-version: 3.9
          auto-activate-base: false

      - name: Build
        uses: actions/checkout@v2
        shell: bash -l {0}
        run: |
          cd ..
          git clone https://github.com/nikhilwoodruff/ubicenter.org
          cd ubicenter.org
          git checkout -b test-branch
          cd ..
          python ./ubicenter.org/post_from_notebook.py analysis-template/website/post.ipynb analysis-template/website/metadata.yml --output-md ubicenter.org/_posts/2021-07-01-test-post.md --output-folder ubicenter.org/assets/markdown_assets/test-post/
          cd ubicenter.org
          git push origin test-branch